# Generated by Django 4.1.3 on 2022-11-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='id телеграм пользователя')),
                ('chat_id', models.BigIntegerField(verbose_name='chat id')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP адрес пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь телеграм',
                'verbose_name_plural': 'Пользователи телеграма',
            },
        ),
    ]
