# Generated by Django 4.1.3 on 2022-11-28 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_telegramuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
