# Generated by Django 4.1.3 on 2022-11-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0003_telegramuser_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлен'),
        ),
    ]
