# Generated by Django 4.1.3 on 2022-11-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0004_alter_telegramuser_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.BigIntegerField(editable=False, verbose_name='id телеграм пользователя'),
        ),
    ]
