# Generated by Django 4.1.3 on 2022-11-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Цена услуги'),
            preserve_default=False,
        ),
    ]
