# Generated by Django 4.1.3 on 2022-11-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='setting',
            name='telegram_bot',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на бот'),
        ),
    ]
