# Generated by Django 4.1.3 on 2022-11-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_setting_address_setting_telegram_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефонный номер')),
                ('subject', models.TextField(verbose_name='Причина обращения')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
