# Generated by Django 4.1.3 on 2022-11-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_aboutusimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=False, help_text='False - не решен, True - решен', verbose_name='Статус обращения'),
        ),
    ]
