# Generated by Django 4.1.3 on 2022-12-02 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_alter_setting_url_maps'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_portfolio', to='settings.portfolio', verbose_name='Портфолио')),
            ],
            options={
                'verbose_name': 'Особенность портфолио',
                'verbose_name_plural': 'Особенности портфолио',
            },
        ),
    ]
