# Generated by Django 4.1.3 on 2022-12-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_portfoliofeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание услуги'),
        ),
    ]
